version: '3'
services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: ./react-app/Dockerfile
    restart: always
    networks:
      - myNetwork
    ports:
      - "80:80"
