version: '3'
services:
  mac_check-app:
    container_name: mac_check
    build:
      context: .
      dockerfile: ./react-app/Dockerfile
    restart: always
    networks:
      - mack-check-Network
    ports:
      - "80:80"

networks:
  mack-check-Network:
    driver: bridge      
